<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGtdlhvi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGtdlhvi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGtdlhvi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGtdlhvi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGtdlhvi\App_KernelDevDebugContainer([
    'container.build_hash' => 'Gtdlhvi',
    'container.build_id' => '4e42fde8',
    'container.build_time' => 1698478152,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGtdlhvi');
