<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJdq7uRF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJdq7uRF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJdq7uRF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJdq7uRF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJdq7uRF\App_KernelDevDebugContainer([
    'container.build_hash' => 'Jdq7uRF',
    'container.build_id' => 'ef7c75b5',
    'container.build_time' => 1697265997,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJdq7uRF');
