<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEaNANMW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEaNANMW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEaNANMW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEaNANMW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEaNANMW\App_KernelDevDebugContainer([
    'container.build_hash' => 'EaNANMW',
    'container.build_id' => '222dcc47',
    'container.build_time' => 1697379417,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEaNANMW');
